name: Action1
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache Dependancies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependancies
        run: npm ci
      - name: Run Tests
        run: npm test
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache Dependancies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependancies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  build:
    needs: [run-test, run-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache Dependancies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependancies
        run: npm ci
      - name: Build file
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  upload:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Extract artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: List file
        run: ls