name: Action1
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependancies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Run Lint
        run: npm run lint
  build-deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependancies
        run: npm ci
      - name: Build file
        run: npm run build
      - name: Deploy
        run: echo 'Deploying app...'
